INSERT INTO song(artist, songName) VALUES ('The Beatles', 'Hey Jude');
INSERT INTO song(artist, songName) VALUES ('Queen', 'Bohemian Rhapsody');
INSERT INTO song(artist, songName) VALUES ('Michael Jackson', 'Billie Jean');
INSERT INTO song(artist, songName) VALUES ('Elvis Presley', 'Cant Help Falling in Love');
INSERT INTO song(artist, songName) VALUES ('Bob Dylan', 'Like a Rolling Stone');
INSERT INTO song(artist, songName) VALUES ('Rolling Stones', 'Satisfaction');
INSERT INTO song(artist, songName) VALUES ('Led Zeppelin', 'Stairway to Heaven');
INSERT INTO song(artist, songName) VALUES ('Pink Floyd', 'Wish You Were Here');
INSERT INTO song(artist, songName) VALUES ('Nirvana', 'Smells Like Teen Spirit');
INSERT INTO song(artist, songName) VALUES ('The Eagles', 'Hotel California');
INSERT INTO song(artist, songName) VALUES ('Johnny Cash', 'Ring of Fire');
INSERT INTO song(artist, songName) VALUES ('ACDC', 'Back in Black');
INSERT INTO song(artist, songName) VALUES ('David Bowie', 'Space Oddity');
INSERT INTO song(artist, songName) VALUES ('Prince', 'Purple Rain');
INSERT INTO song(artist, songName) VALUES ('The Beach Boys', 'Good Vibrations');
INSERT INTO song(artist, songName) VALUES ('The Rolling Stones', 'Paint It Black');
INSERT INTO song(artist, songName) VALUES ('Bob Marley', 'No Woman, No Cry');
INSERT INTO song(artist, songName) VALUES ('Jimi Hendrix', 'Purple Haze');
INSERT INTO song(artist, songName) VALUES ('Bruce Springsteen', 'Born to Run');
INSERT INTO song(artist, songName) VALUES ('U2', 'With or Without You');
INSERT INTO song(artist, songName) VALUES ('The Police', 'Every Breath You Take');
INSERT INTO song(artist, songName) VALUES ('Frank Sinatra', 'My Way');
INSERT INTO song(artist, songName) VALUES ('Stevie Wonder', 'Superstition');
INSERT INTO song(artist, songName) VALUES ('Queen', 'We Will Rock You');
INSERT INTO song(artist, songName) VALUES ('The Beatles', 'Let It Be');
INSERT INTO song(artist, songName) VALUES ('Elton John', 'Rocket Man');
INSERT INTO song(artist, songName) VALUES ('Pink Floyd', 'Another Brick in the Wall');
INSERT INTO song(artist, songName) VALUES ('John Lennon', 'Imagine');
INSERT INTO song(artist, songName) VALUES ('The Doors', 'Light My Fire');
INSERT INTO song(artist, songName) VALUES ('Metallica', 'Enter Sandman');
INSERT INTO song(artist, songName) VALUES ('Elvis Presley', 'Jailhouse Rock');
INSERT INTO song(artist, songName) VALUES ('The Who', 'Baba ORiley');
INSERT INTO song(artist, songName) VALUES ('The Rolling Stones', 'Sympathy for the Devil');
INSERT INTO song(artist, songName) VALUES ('Johnny Cash', 'Folsom Prison Blues');
INSERT INTO song(artist, songName) VALUES ('The Clash', 'London Calling');
INSERT INTO song(artist, songName) VALUES ('Guns N Roses', 'Sweet Child o Mine');
INSERT INTO song(artist, songName) VALUES ('Bob Dylan', 'Knockin on Heavens Door');
INSERT INTO song(artist, songName) VALUES ('ACDC', 'Highway to Hell');
INSERT INTO song(artist, songName) VALUES ('Radiohead', 'Creep');
INSERT INTO song(artist, songName) VALUES ('David Bowie', 'Heroes');
INSERT INTO song(artist, songName) VALUES ('Led Zeppelin', 'Whole Lotta Love');
INSERT INTO song(artist, songName) VALUES ('The Beatles', 'Yesterday');
INSERT INTO song(artist, songName) VALUES ('Nirvana', 'Come as You Are');
INSERT INTO song(artist, songName) VALUES ('Queen', 'Another One Bites the Dust');
INSERT INTO song(artist, songName) VALUES ('Pink Floyd', 'Comfortably Numb');
INSERT INTO song(artist, songName) VALUES ('The Rolling Stones', 'Gimme Shelter');
INSERT INTO song(artist, songName) VALUES ('The Doors', 'Riders on the Storm');
INSERT INTO song(artist, songName) VALUES ('Jimi Hendrix', 'All Along the Watchtower');
INSERT INTO song(artist, songName) VALUES ('Metallica', 'Nothing Else Matters');