INSERT INTO artist (name) VALUES
  ('The Beatles'),
  ('Pink Floyd'),
  ('Michael Jackson'),
  ('AC/DC'),
  ('Led Zeppelin'),
  ('Eagles'),
  ('Fleetwood Mac'),
  ('U2'),
  ('The Beach Boys'),
  ('Lana Del Rey'),
  ('Nirvana'),
  ('Queen'),
  ('Radiohead'),
  ('The Velvet Underground'),
  ('The Rolling Stones'),
  ('Black Sabbath'),
  ('David Bowie'),
  ('The Doors'),
  ('Metallica'),
  ('Coldplay');