INSERT INTO artist_albums (albums_id, artists_id) VALUES
      (1, 1),  -- Artist 1 (The Beatles) associated with Album 1 (Abbey Road)
      (2, 2),  -- Artist 2 (Pink Floyd) associated with Album 2 (The Dark Side of the Moon)
      (3, 3),  -- Artist 3 (Michael Jackson) associated with Album 3 (Thriller)
      (4, 4),  -- Artist 4 (AC/DC) associated with Album 4 (Back in Black)
      (5, 5),  -- Artist 5 (Led Zeppelin) associated with Album 5 (Led Zeppelin IV)
      (6, 6),  -- Artist 6 (Eagles) associated with Album 6 (Hotel California)
      (7, 7),  -- Artist 7 (Fleetwood Mac) associated with Album 7 (Rumours)
      (8, 8),  -- Artist 8 (U2) associated with Album 8 (The Joshua Tree)
      (9, 9),  -- Artist 9 (The Beach Boys) associated with Album 9 (Sgt. Pepper's Lonely Hearts Club Band)
      (10, 10),  -- Artist 10 (Lana Del Rey) associated with Album 10 (Born to Die)
      (11, 11),  -- Artist 11 (Nirvana) associated with Album 11 (Nevermind)
      (12, 12),  -- Artist 12 (Queen) associated with Album 12 (Pet Sounds)
      (13, 13),  -- Artist 13 (Pink Floyd) associated with Album 13 (Another Abbey Road)
      (14, 14),  -- Artist 14 (Queen) associated with Album 14 (A Night at the Opera)
      (15, 15),  -- Artist 15 (Pink Floyd) associated with Album 15 (The Wall)
      (16, 16),  -- Artist 16 (The Beatles) associated with Album 16 (The White Album)
      (17, 17),  -- Artist 17 (Radiohead) associated with Album 17 (OK Computer)
      (18, 18),  -- Artist 18 (The Velvet Underground) associated with Album 18 (The Velvet Underground & Nico)
      (19, 19),  -- Artist 19 (The Rolling Stones) associated with Album 19 (Rubber Soul)
      (20, 20);  -- Artist 20 (Radiohead) associated with Album 20 (Darkness on the Edge of Town)